# dataset
data_path: "./data"
input_len: 144 
output_len: 288
# var_len: 13
var_len: 10
capacity: 134
patient: 2 


num_workers: 4
epoch: 10 
batch_size: 32 
output_path: "./output/baseline"
log_per_steps: 100
lr: 0.0001

# Model
model:
    hidden_dims: 32 
    nhead: 8
    dropout: 0.5
    encoder_layers: 2
    decoder_layers: 1

loss:
    name: "MSELoss"
